/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import dao.Cocherasdao;
import dao.cocheras;
import fachada.fachada;
import javax.swing.JOptionPane;
import mapeo.Cochera;

/**
 *
 * @author Usuario
 */
public class prueba extends javax.swing.JFrame {

fachada f = new fachada();
    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estaciones = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstaciones = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNuevaEstacion = new javax.swing.JButton();
        btnGuardarEstacion = new javax.swing.JButton();
        btnEliminarEstacion = new javax.swing.JButton();
        btnModificarEstacion = new javax.swing.JButton();
        btnSalirEstacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreEstacion = new javax.swing.JTextField();
        txtLocalidadEstacion = new javax.swing.JTextField();
        txtDireccionEstacion = new javax.swing.JTextField();
        txtCodigoPostalEstacion = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoEstacion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTrenes = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        btnLineas = new javax.swing.JButton();
        btnEstaciones = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        tbEstaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbEstaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEstaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEstacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEstaciones);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNuevaEstacion.setText("Nuevo");

        btnGuardarEstacion.setText("Guardar");
        btnGuardarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEstacionActionPerformed(evt);
            }
        });

        btnEliminarEstacion.setText("Eliminar");
        btnEliminarEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstacionActionPerformed(evt);
            }
        });

        btnModificarEstacion.setText("Modificar");

        btnSalirEstacion.setText("Salir");
        btnSalirEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirEstacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNuevaEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnGuardarEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificarEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnSalirEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaEstacion)
                    .addComponent(btnGuardarEstacion)
                    .addComponent(btnEliminarEstacion)
                    .addComponent(btnModificarEstacion)
                    .addComponent(btnSalirEstacion))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel2.setText("Dirección:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("ZIP:");

        jLabel6.setText("Localidad:");

        try {
            txtCodigoPostalEstacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Código:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLocalidadEstacion, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtCodigoPostalEstacion))
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtLocalidadEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPostalEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EstacionesLayout = new javax.swing.GroupLayout(Estaciones.getContentPane());
        Estaciones.getContentPane().setLayout(EstacionesLayout);
        EstacionesLayout.setHorizontalGroup(
            EstacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        EstacionesLayout.setVerticalGroup(
            EstacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTrenes.setForeground(new java.awt.Color(0, 51, 255));
        btnTrenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tren.png"))); // NOI18N
        btnTrenes.setText("TRENES");
        btnTrenes.setBorderPainted(false);
        btnTrenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrenes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrenes.setIconTextGap(14);
        btnTrenes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnTrenes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTrenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrenesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 170));

        btnViajes.setForeground(new java.awt.Color(0, 51, 255));
        btnViajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/viaje.png"))); // NOI18N
        btnViajes.setText("VIAJES");
        btnViajes.setBorderPainted(false);
        btnViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViajes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViajes.setIconTextGap(14);
        btnViajes.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnViajes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesActionPerformed(evt);
            }
        });
        jPanel1.add(btnViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 170, 170));

        btnLineas.setForeground(new java.awt.Color(0, 51, 255));
        btnLineas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trentrasnparente.png"))); // NOI18N
        btnLineas.setText("LINEAS");
        btnLineas.setBorderPainted(false);
        btnLineas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLineas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLineas.setIconTextGap(14);
        btnLineas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLineas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineasActionPerformed(evt);
            }
        });
        jPanel1.add(btnLineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 170, 170));

        btnEstaciones.setForeground(new java.awt.Color(0, 51, 255));
        btnEstaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estacion.png"))); // NOI18N
        btnEstaciones.setText("ESTACIONES");
        btnEstaciones.setBorderPainted(false);
        btnEstaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstaciones.setIconTextGap(14);
        btnEstaciones.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnEstaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Camino de vias de trenes-232925.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstacionesActionPerformed
       this.Estaciones.setVisible(true);

       
       
    }//GEN-LAST:event_btnEstacionesActionPerformed

    private void btnLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineasActionPerformed
        
    }//GEN-LAST:event_btnLineasActionPerformed

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        
    }//GEN-LAST:event_btnViajesActionPerformed

    private void btnTrenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrenesActionPerformed
       
    }//GEN-LAST:event_btnTrenesActionPerformed

    private void btnGuardarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEstacionActionPerformed
        if(f.addEstaciones(this.txtNombreEstacion.getText(), this.txtLocalidadEstacion.getText(), this.txtDireccionEstacion.getText(), Integer.parseInt(this.txtCodigoPostalEstacion.getText()))){
            this.tbEstaciones.setModel(f.TablaEstaciones());
            JOptionPane.showMessageDialog(null, "Estacion Creada");
        }else{
            JOptionPane.showMessageDialog(null, "Error al insertar");
        }
    }//GEN-LAST:event_btnGuardarEstacionActionPerformed

    private void btnEliminarEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstacionActionPerformed
        
    }//GEN-LAST:event_btnEliminarEstacionActionPerformed

    private void tbEstacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEstacionesMouseClicked
        int fila = this.tbEstaciones.rowAtPoint(evt.getPoint());
            if (fila > -1){                
                this.txtCodigoEstacion.setText( String.valueOf( this.tbEstaciones.getValueAt(fila, 0) ));
            }        
    }//GEN-LAST:event_tbEstacionesMouseClicked

    private void btnSalirEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirEstacionActionPerformed
        Estaciones.dispose();
    }//GEN-LAST:event_btnSalirEstacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog Estaciones;
    public javax.swing.JButton btnEliminarEstacion;
    public javax.swing.JButton btnEstaciones;
    public javax.swing.JButton btnGuardarEstacion;
    public javax.swing.JButton btnLineas;
    public javax.swing.JButton btnModificarEstacion;
    public javax.swing.JButton btnNuevaEstacion;
    public javax.swing.JButton btnSalirEstacion;
    public javax.swing.JButton btnTrenes;
    public javax.swing.JButton btnViajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbEstaciones;
    private javax.swing.JTextField txtCodigoEstacion;
    public javax.swing.JFormattedTextField txtCodigoPostalEstacion;
    public javax.swing.JTextField txtDireccionEstacion;
    public javax.swing.JTextField txtLocalidadEstacion;
    public javax.swing.JTextField txtNombreEstacion;
    // End of variables declaration//GEN-END:variables
}
