package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1



/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private AccesoId id;
     private Estacion estacion;
     private String entrada;

    public Acceso() {
    }

	
    public Acceso(AccesoId id, Estacion estacion) {
        this.id = id;
        this.estacion = estacion;
    }
    public Acceso(AccesoId id, Estacion estacion, String entrada) {
       this.id = id;
       this.estacion = estacion;
       this.entrada = entrada;
    }
   
    public AccesoId getId() {
        return this.id;
    }
    
    public void setId(AccesoId id) {
        this.id = id;
    }
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }
    public String getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(String entrada) {
        this.entrada = entrada;
    }




}


