package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion  implements java.io.Serializable {


     private Integer codEstacion;
     private String nombre;
     private String localidad;
     private String direccion;
     private int codPostal;
     private Set lineaestacions = new HashSet(0);
     private Set accesos = new HashSet(0);
     private Set viajesForEstacionCodEstacion1 = new HashSet(0);
     private Set viajesForEstacionCodEstacion = new HashSet(0);

    public Estacion() {
    }

	
    public Estacion(String nombre, String localidad, String direccion, int codPostal) {
        this.nombre = nombre;
        this.localidad = localidad;
        this.direccion = direccion;
        this.codPostal = codPostal;
    }
    public Estacion(String nombre, String localidad, String direccion, int codPostal, Set lineaestacions, Set accesos, Set viajesForEstacionCodEstacion1, Set viajesForEstacionCodEstacion) {
       this.nombre = nombre;
       this.localidad = localidad;
       this.direccion = direccion;
       this.codPostal = codPostal;
       this.lineaestacions = lineaestacions;
       this.accesos = accesos;
       this.viajesForEstacionCodEstacion1 = viajesForEstacionCodEstacion1;
       this.viajesForEstacionCodEstacion = viajesForEstacionCodEstacion;
    }
   
    public Integer getCodEstacion() {
        return this.codEstacion;
    }
    
    public void setCodEstacion(Integer codEstacion) {
        this.codEstacion = codEstacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(int codPostal) {
        this.codPostal = codPostal;
    }
    public Set getLineaestacions() {
        return this.lineaestacions;
    }
    
    public void setLineaestacions(Set lineaestacions) {
        this.lineaestacions = lineaestacions;
    }
    public Set getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set accesos) {
        this.accesos = accesos;
    }
    public Set getViajesForEstacionCodEstacion1() {
        return this.viajesForEstacionCodEstacion1;
    }
    
    public void setViajesForEstacionCodEstacion1(Set viajesForEstacionCodEstacion1) {
        this.viajesForEstacionCodEstacion1 = viajesForEstacionCodEstacion1;
    }
    public Set getViajesForEstacionCodEstacion() {
        return this.viajesForEstacionCodEstacion;
    }
    
    public void setViajesForEstacionCodEstacion(Set viajesForEstacionCodEstacion) {
        this.viajesForEstacionCodEstacion = viajesForEstacionCodEstacion;
    }




}


