package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1



/**
 * LineaestacionId generated by hbm2java
 */
public class LineaestacionId  implements java.io.Serializable {


     private int estacionCodEstacion;
     private int lineaCodLinea;

    public LineaestacionId() {
    }

    public LineaestacionId(int estacionCodEstacion, int lineaCodLinea) {
       this.estacionCodEstacion = estacionCodEstacion;
       this.lineaCodLinea = lineaCodLinea;
    }
   
    public int getEstacionCodEstacion() {
        return this.estacionCodEstacion;
    }
    
    public void setEstacionCodEstacion(int estacionCodEstacion) {
        this.estacionCodEstacion = estacionCodEstacion;
    }
    public int getLineaCodLinea() {
        return this.lineaCodLinea;
    }
    
    public void setLineaCodLinea(int lineaCodLinea) {
        this.lineaCodLinea = lineaCodLinea;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LineaestacionId) ) return false;
		 LineaestacionId castOther = ( LineaestacionId ) other; 
         
		 return (this.getEstacionCodEstacion()==castOther.getEstacionCodEstacion())
 && (this.getLineaCodLinea()==castOther.getLineaCodLinea());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEstacionCodEstacion();
         result = 37 * result + this.getLineaCodLinea();
         return result;
   }   


}


