package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1



/**
 * Lineaestacion generated by hbm2java
 */
public class Lineaestacion  implements java.io.Serializable {


     private LineaestacionId id;
     private Estacion estacion;
     private Linea linea;
     private int orden;

    public Lineaestacion() {
    }

    public Lineaestacion(LineaestacionId id, Estacion estacion, Linea linea, int orden) {
       this.id = id;
       this.estacion = estacion;
       this.linea = linea;
       this.orden = orden;
    }
   
    public LineaestacionId getId() {
        return this.id;
    }
    
    public void setId(LineaestacionId id) {
        this.id = id;
    }
    public Estacion getEstacion() {
        return this.estacion;
    }
    
    public void setEstacion(Estacion estacion) {
        this.estacion = estacion;
    }
    public Linea getLinea() {
        return this.linea;
    }
    
    public void setLinea(Linea linea) {
        this.linea = linea;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


