package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1



/**
 * TrenId generated by hbm2java
 */
public class TrenId  implements java.io.Serializable {


     private int codTren;
     private int lineaCodLinea;
     private int cocheraCodCochera;

    public TrenId() {
    }

    public TrenId(int codTren, int lineaCodLinea, int cocheraCodCochera) {
       this.codTren = codTren;
       this.lineaCodLinea = lineaCodLinea;
       this.cocheraCodCochera = cocheraCodCochera;
    }
   
    public int getCodTren() {
        return this.codTren;
    }
    
    public void setCodTren(int codTren) {
        this.codTren = codTren;
    }
    public int getLineaCodLinea() {
        return this.lineaCodLinea;
    }
    
    public void setLineaCodLinea(int lineaCodLinea) {
        this.lineaCodLinea = lineaCodLinea;
    }
    public int getCocheraCodCochera() {
        return this.cocheraCodCochera;
    }
    
    public void setCocheraCodCochera(int cocheraCodCochera) {
        this.cocheraCodCochera = cocheraCodCochera;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrenId) ) return false;
		 TrenId castOther = ( TrenId ) other; 
         
		 return (this.getCodTren()==castOther.getCodTren())
 && (this.getLineaCodLinea()==castOther.getLineaCodLinea())
 && (this.getCocheraCodCochera()==castOther.getCocheraCodCochera());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodTren();
         result = 37 * result + this.getLineaCodLinea();
         result = 37 * result + this.getCocheraCodCochera();
         return result;
   }   


}


