package mapeo;
// Generated 30-nov-2016 14:10:39 by Hibernate Tools 4.3.1



/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private ViajeId id;
     private Estacion estacionByEstacionCodEstacion1;
     private Estacion estacionByEstacionCodEstacion;
     private String ciudad;

    public Viaje() {
    }

    public Viaje(ViajeId id, Estacion estacionByEstacionCodEstacion1, Estacion estacionByEstacionCodEstacion, String ciudad) {
       this.id = id;
       this.estacionByEstacionCodEstacion1 = estacionByEstacionCodEstacion1;
       this.estacionByEstacionCodEstacion = estacionByEstacionCodEstacion;
       this.ciudad = ciudad;
    }
   
    public ViajeId getId() {
        return this.id;
    }
    
    public void setId(ViajeId id) {
        this.id = id;
    }
    public Estacion getEstacionByEstacionCodEstacion1() {
        return this.estacionByEstacionCodEstacion1;
    }
    
    public void setEstacionByEstacionCodEstacion1(Estacion estacionByEstacionCodEstacion1) {
        this.estacionByEstacionCodEstacion1 = estacionByEstacionCodEstacion1;
    }
    public Estacion getEstacionByEstacionCodEstacion() {
        return this.estacionByEstacionCodEstacion;
    }
    
    public void setEstacionByEstacionCodEstacion(Estacion estacionByEstacionCodEstacion) {
        this.estacionByEstacionCodEstacion = estacionByEstacionCodEstacion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


